[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_plays_pokemon_program = "pkmJNXmUxFT1bmmCp4DgvCm2LxR3afRtCwV1EzQwEHK"

[programs.devnet]
solana_plays_pokemon_program = "pkmJNXmUxFT1bmmCp4DgvCm2LxR3afRtCwV1EzQwEHK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/nelson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
